openapi: 3.0.0
info:
  version: 1.0.0
  title: Client Survey Repository API
  description: Client Survey Repository API
  termsOfService: http://swagger.io/terms/
  contact:
    name: API Team
    email: apiteam@eoc.io
    url: http://eoc.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://eoc-survey-repository.infra-workers.workers.dev/
  - url: http://localhost:8787
paths:
  /survey:
    get:
      tags:
        - SurveyRepository
      summary: Returns all Surveys from the system that the user has access to
      description: Returns all Surveys from the system that the user has access to
      operationId: findSurvey
      parameters:
        - schema:
            type: number
            description: Page number
          required: true
          description: Page number
          name: page
          in: query
        - schema:
            type: boolean
            description: Filter by completed flag
          required: false
          description: Filter by completed flag
          name: isCompleted
          in: query
      responses:
        '200':
          description: Survey response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Survey'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - SurveyRepository
      summary: Creates \ Update a new Survey in the store.  Duplicates are not allowed
      description: Creates \ Update a new Survey in the store.  Duplicates are not allowed
      operationId: addOrUpdateSurvey
      requestBody:
        description: Survey to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Survey'
      responses:
        '200':
          description: Survey response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Survey'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /survey/{id}:
    get:
      tags:
        - SurveyRepository
      summary: Returns a Survey based on a single ID
      description: Returns a Survey based on a single ID
      operationId: findSurveyById
      parameters:
        - name: id
          in: path
          description: ID of Survey to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Survey response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Survey'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - SurveyRepository
      summary: deletes a single Survey based on the ID supplied
      description: deletes a single Survey based on the ID supplied
      operationId: deleteSurvey
      parameters:
        - name: id
          in: path
          description: ID of Survey to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Survey deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    Survey:
      type: object
      properties:
        surveyId:
          type: string
        state:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
security:
  - bearerAuth: [] 